# Generated by Django 3.2 on 2021-04-29 15:19

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorldBorders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('area', models.IntegerField()),
                ('pop2005', models.IntegerField(verbose_name='Population 2005')),
                ('fips', models.CharField(max_length=2, null=True, verbose_name='FIPS code')),
                ('iso2', models.CharField(max_length=2, verbose_name='2 digits ISO')),
                ('iso3', models.CharField(max_length=3, verbose_name='3 digits ISO')),
                ('un', models.IntegerField(verbose_name='United Nation code')),
                ('region', models.IntegerField(verbose_name='Region code')),
                ('subregion', models.IntegerField(verbose_name='Sub-region code')),
                ('mpoly', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
    ]
