# Generated by Django 3.2 on 2021-04-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('world', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='worldborders',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='worldborders',
            name='lon',
            field=models.FloatField(null=True),
        ),
    ]
